local_backend: true

logo_url: /logo.svg

backend:
    name: github
    branch: main
    repo: hectorAguero/astro-starter
    site_domain: astro-starter-uw0.pages.dev
    base_url: https://astro-starter-uw0.pages.dev/
    auth_endpoint: /api/auth
    automatic_deployments: true

media_folder: static/img
public_folder: /img

i18n:
    structure: "multiple_folders"
    locales:
        - "es"
        - "pt"
    default_locale: "es"

collections:
    - name: "posts"
      i18n: true
      label: "Blog Posts"
      folder: "src/content/blog"
      media_folder: "/src/assets/images/blog"
      public_folder: "@assets/images/blog"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
            i18n: true
          - label: "Description"
            name: "description"
            widget: "string"
            i18n: true
          - label: "Publish Date"
            name: "pubDate"
            widget: "datetime"
            format: "YYYY-MM-DD HH:mm"
            i18n: "duplicate"
          - label: "Image"
            name: "heroImage"
            widget: "image"
            i18n: "duplicate"
          - name: "body"
            widget: "markdown"
            label: "Post Body"
            i18n: true
